@level_01_HostAddress = http://localhost:5019

GET {{level_01_HostAddress}}/api/Product
Accept: application/json


###

GET {{level_01_HostAddress}}/api/Product/1
Accept: application/json

###

POST {{level_01_HostAddress}}/api/Product
Content-Type: application/json

{
  "id": 7,
  "name": "Product-07",
  "price": 700,
  "stock": 70
}

###

PUT {{level_01_HostAddress}}/api/Product
Content-Type: application/json

{
  "name": "Product-07",
  "price": 700,
  "stock": 70
}

###
DELETE {{level_01_HostAddress}}/api/Product/18
Accept: application/json

###